---
title: "Guarding Health and Wealth"
subtitle: "Examining The Interplay Between GDP, Insecticide Treated Mosquito Nets and Life Expectancy"
author: "Robert Timmons"
date: "03/04/2024"
format: html
---

```{r}
#| label: setup
#| include: false

#libraries
library(readr)
library(tidyverse)
library(maps)
library(dplyr)
library(plotly)
library(ggplot2)

#data
unicef_indicator_2 <- read_csv("unicef_indicator_2.csv")
unicef_metadata <- read_csv("unicef_metadata.csv")

#transformations
data_join <- full_join(unicef_indicator_2, unicef_metadata)
data_join <- full_join(unicef_indicator_2, unicef_metadata, by = "country")

```

```{r}
#World map
map_world <- map_data("world")

map_data_join <- full_join(unicef_indicator_2, map_world, by = c("country" = "region"))

ggplot(map_data_join) +
  aes(x = long, y = lat, group = group, fill = obs_value) +
  geom_polygon() +
  scale_fill_gradient(low = "red" , high = "darkblue", name = "% of ITMN") +  
  labs(fill = "obs_value") + 
  labs(x = "latitude",
       y = "longitude", 
       title = "% Of households with atleast one or more Insecticide Treated Mosquito Nets") +
  theme_void() +
  theme(text = element_text(family = "serif", size = 12))

```

```{r}
#Time series
selected_countries <- c("Guinea-Bissau", "Niger", "Mali","Tanzania, United Republic of","Uganda")
filtered_data <- data_join %>%
  filter(country %in% selected_countries)

time_series_plot_filtered <- filtered_data %>%
  ggplot()+
  aes(time_period, obs_value, group = country, color = country) +
  geom_line() +
  labs(x= "years", 
       y = "% of households with at least one ITMN", 
       title = "The growth in adoption of ITMNS between 2005 and 2021") +
  theme_classic() +
  theme(text = element_text(family = "serif", size = 12))


ggplotly(time_series_plot_filtered)

```

```{r}
#Scatter plot
filtered_data <- data_join %>%
  filter(year == 2015)

scatter_plot <- ggplot(filtered_data) +
  aes(x = obs_value, y = `Life expectancy at birth, total (years)`, color = country) +
  geom_point(alpha = 2, show.legend = FALSE) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE, color = "black", linewidth = 0.5) +
  scale_x_continuous(
    limits = c(0, 100),
    breaks = c(25, 50, 75, 100), 
    labels = scales::unit_format(unit = "%", scale = 1)
  ) +
  scale_size_continuous(guide = FALSE) +
  labs(x = "% of households with at least one Insecticide Treated Mosquito Net (ITMN)",
       y = "Life expectancy at birth", 
       title = "An analysis of the relationship between life expectancy and the use of ITMNs in 2015") +
  guides(color = "none", size = "none") +
  theme_classic() +
  theme(text = element_text(family = "serif", size = 12))

ggplotly(scatter_plot)


```

```{r}
#Barchart
chart_join <- full_join(unicef_indicator_2, unicef_metadata, by = c("country", "time_period" = "year"))


filtered_data <- chart_join %>%
  filter(time_period == 2021,
         country %in% c("Guinea-Bissau", "Niger", "Mali", "Tanzania, United Republic of", "Uganda")) %>%
  group_by(country, time_period) %>%
  summarise(m_lifeExp = mean(`Life expectancy at birth, total (years)`, na.rm = TRUE))

p <- ggplot(filtered_data) +
  aes(x = country, y = m_lifeExp, fill = country) +
  geom_col() +
  guides(fill = FALSE) +
  labs(x = "Countries", 
       y = "Average Life Expectancy", 
       title = "Affected countries and their life expectancy in 2021") +
  theme_classic() +
  theme(text = element_text(family = "serif", size = 12), axis.text.x = element_text(angle = 0, hjust = 1))

ggplotly(p)
```